language: java
addons:
  ssh_known_hosts: ovz1.iutin1999.pqj7n.vps.myjino.ru
before_install:
- openssl aes-256-cbc -K $encrypted_060bfcf8ce8c_key -iv $encrypted_060bfcf8ce8c_iv
  -in .travis/id_rsa_deploy.enc -out .travis/id_rsa_deploy -d
script:
- mvn clean package
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa_deploy
  - ssh-add .travis/id_rsa_deploy
  - ssh root@ovz1.iutin1999.pqj7n.vps.myjino.ru cd tomcat/test
  - ssh root@ovz1.iutin1999.pqj7n.vps.myjino.ru git clone https://github.com/Salikhov12/calculator
