language: java
addons:
  ssh_known_hosts: ovz1.iutin1999.pqj7n.vps.myjino.ru:49290
before_install:
- openssl aes-256-cbc -K $encrypted_060bfcf8ce8c_key -iv $encrypted_060bfcf8ce8c_iv
  -in .travis/id_rsa_deploy.enc -out .travis/id_rsa_deploy -d
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa_deploy
  - ssh-add .travis/id_rsa_deploy
deploy:
  provider: script
  script: mvn clean package && ssh root@ovz1.iutin1999.pqj7n.vps.myjino.ru ls -l
  on:
    branch: test1
