language: java
addons:
  ssh_known_hosts: ovz1.iutin1999.pqj7n.vps.myjino.ru:49290
before_install:
- openssl aes-256-cbc -K $encrypted_060bfcf8ce8c_key -iv $encrypted_060bfcf8ce8c_iv
  -in .travis/id_rsa_deploy.enc -out .travis/id_rsa_deploy -d
script: mvn clean package
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa_deploy
  - ssh-add .travis/id_rsa_deploy
  - ssh-keygen -f "/home/travis/.ssh/known_hosts" -R ovz1.iutin1999.pqj7n.vps.myjino.ru
  - yes
  - ssh root@ovz1.iutin1999.pqj7n.vps.myjino.ru ls -l
